### PR TITLE
Proofreading

### PR DESCRIPTION
**Pull request by PassionPenguin**
@lsvih @itcodes please take a look, thanks :)

### CODE REVIEW

**Comment by lsvih** [comment]
LSTM, could you please split this huge PR into multiple smaller PRs containing just a few articles each to make them easier to process?

**Comment by PassionPenguin** [comment]
> LGTM, could you please split this huge PR into multiple smaller PRs containing just a few articles each to make them easier to process?

well…. Could be hard….lol

**Comment by PassionPenguin** [comment]
(should i create individual pr for each article? that would be a big job, plus making pr logs dirty...

**Comment by PassionPenguin** [comment]
it could be a very easy job with git cherry-pick and `gh` pr creation, but…? CC @lsvih

**Pull request closed without merging**
